version: '3.1'
services:
  stats-server:
    build: ./statistics
    ports:
      - "9090:9090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ExploreWithMeStats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - dbStats
  stats-db:
    image: postgres:14-alpine
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ExploreWithMeStats
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  ewm-service:
    build: ./server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ExploreWithMe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    depends_on:
      - db
  ewm-db:
    image: postgres:14-alpine
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ExploreWithMe
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
