CREATE TABLE IF NOT EXISTS endpoint_hit
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    app        VARCHAR,
    uri        VARCHAR,
    ip         VARCHAR,
    time_stamp TIMESTAMP WITHOUT TIME ZONE
);
